name: Build .NET

on:
  workflow_call:
    inputs:
      sln-path:
        description: 'Path to the solution/project file'
        default: '.'

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    name: Build .NET
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Install dependencies
        working-directory: ./src/Net
        run: dotnet restore

      - name: Build
        working-directory: ./src/Net
        run: dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: ./src/Net
        run: dotnet test --no-restore --verbosity normal
