name: Build .NET

on:
  workflow_call:
    inputs:
      work-dir:
        description: "Path to the solution/project file"
        required: false
        type: string
        default: "."

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    name: Build .NET
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Install dependencies
        working-directory: ${{ inputs.work-dir }}
        run: dotnet restore

      - name: Build
        working-directory: ${{ inputs.work-dir }}
        run: dotnet build --configuration Release --no-restore

      - name: Test
        working-directory: ${{ inputs.work-dir }}
        run: dotnet test --no-restore --verbosity normal
